site_name: 'watched.js'
theme: 'bootstrap'
theme_dir: 'custom_theme'
repo_url: 'https://github.com/grmlin/watched'
site_author: 'Andreas Wehr'
markdown_extensions: [fenced_code, meta, def_list]
extra_javascript: ['js/watched.js', 'js/demo.js']

pages:
- ['index.md', 'GREMLIN.JS']
- ['api.md', 'Documentation']
- ['demo.html', 'Demo']